# Generated by Django 5.0.14 on 2026-06-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', 'USD ($)'), ('₹', 'INR (₹)'), ('€', 'EUR (€)'), ('£', 'GBP (£)'), ('¥', 'JPY (¥)'), ('A$', 'AUD (A$)'), ('C$', 'CAD (C$)'), ('AED', 'AED'), ('SAR', 'SAR')], default='$', max_length=10),
        ),
    ]
